server:
  port: 8070
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.23.239:3306/s1?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password:
  application:
    name: service-provider
  cloud:
    nacos:
      server-addr: 192.168.23.239:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8720
    alibaba:
      seata:
        # 事务分组 config.txt中的service.vgroupMapping.xxx其中的xxx为此处值
        tx-service-group: default_tx_group
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.23.239:8848
      application: seata-server
      group: SEATA_GROUP
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: 192.168.23.239:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos

mybatis:
  mapper-locations: classpath*:mapper/*:xml