#server:
#  port: 8070
#spring:
#  application:
#    name: service-provider
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.23.239:8848
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#        port: 8720